lookahead_distance : 0.24 #one bakma mesafesi
speed : 0.18 #maksimum hiz
expansion_size : 5 #duvar genisletme katsayisi
target_error : 0.15 #hedefe olan hata payi
robot_r : 0.4 #lokal guvenlik icin robot mesafesi
